language: python
os: linux
python:
    - 2.7
addons:
    apt:
        packages:
            - libhdf5-dev
            - mpich
install:
    - "pip install -r requirements.txt"
    - "pip install -e git+https://github.com/zuoshifan/cora.git#egg=cora"
    - "pip install -e git+https://github.com/zuoshifan/caput.git@zuo/develop#egg=caput"
    - "pip install -e git+https://github.com/zuoshifan/aipy.git@zuo/develop#egg=aipy"
# script:
    # - "sphinx-build -b html -d _build/doctrees   . _build/html"
    # - "cd ~; nosetests tlpipe"