language: python
os: linux
python:
    - 2.7
addons:
    apt:
        packages:
            - libhdf5-dev
            - mpich
install:
    - "pip install -r requirements.txt"
# script:
    # - "sphinx-build -b html -d _build/doctrees   . _build/html"
    # - "cd ~; nosetests tlpipe"